using System.Globalization;
using System.Security.Claims;
using HN_Nexus.WebPOS.Data;
using HN_Nexus.WebPOS.Models;
using HN_Nexus.WebPOS.Services;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.HttpOverrides;
using Microsoft.EntityFrameworkCore;
using QuestPDF.Infrastructure;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddDbContext<AppDbContext>(opt =>
    opt.UseNpgsql(builder.Configuration.GetConnectionString("Default")));

builder.Services.AddHttpContextAccessor();
builder.Services.AddScoped<IModuleAccessService, ModuleAccessService>();
builder.Services.AddScoped<IUserContextService, UserContextService>();
builder.Services.AddScoped<IReportPdfService, ReportPdfService>();
builder.Services.AddScoped<ICfdiVaultService, CfdiVaultService>();
builder.Services.AddScoped<IAlertEmailService, AlertEmailService>();
builder.Services.Configure<ForwardedHeadersOptions>(options =>
{
    options.ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto;
    options.KnownNetworks.Clear();
    options.KnownProxies.Clear();
});

builder.Services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme)
    .AddCookie(options =>
    {
        options.LoginPath = "/Account/Login";
        options.AccessDeniedPath = "/Account/Denied";
        options.Cookie.Name = "HNNexus.WebPOS.Auth";
        options.SlidingExpiration = true;
        options.ExpireTimeSpan = TimeSpan.FromHours(8);
    });

builder.Services.AddAuthorization(options =>
{
    options.AddPolicy("AdminOnly", policy => policy.RequireAssertion(ctx =>
        ctx.User.IsInRole("Admin") || ctx.User.IsInRole("SuperUser")));
    options.AddPolicy("SuperOnly", policy => policy.RequireClaim(ClaimTypes.Role, "SuperUser"));
});

builder.Services.AddRazorPages(options =>
{
    options.Conventions.AuthorizeFolder("/");
    options.Conventions.AllowAnonymousToFolder("/Account");
    options.Conventions.AuthorizeFolder("/Config", "AdminOnly");
});

var moduleRoutes = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
{
    ["/"] = ModuleCatalog.Dashboard,
    ["/Index"] = ModuleCatalog.Dashboard,
    ["/Sales"] = ModuleCatalog.Sales,
    ["/Products"] = ModuleCatalog.Products,
    ["/Customers"] = ModuleCatalog.Customers,
    ["/Expenses"] = ModuleCatalog.Expenses,
    ["/CashCuts"] = ModuleCatalog.CashCuts,
    ["/CashShifts"] = ModuleCatalog.CashShifts,
    ["/SupplierOrders"] = ModuleCatalog.SupplierOrders,
    ["/Reports"] = ModuleCatalog.Reports,
    ["/Inventory"] = ModuleCatalog.Products,
    ["/Config"] = ModuleCatalog.Config
};

var mx = new CultureInfo("es-MX");
CultureInfo.DefaultThreadCurrentCulture = mx;
CultureInfo.DefaultThreadCurrentUICulture = mx;

QuestPDF.Settings.License = LicenseType.Community;

var app = builder.Build();
var alertSync = new object();
var lastAlertUtc = DateTime.MinValue;

using (var scope = app.Services.CreateScope())
{
    var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();
    await db.Database.EnsureCreatedAsync();

    await db.Database.ExecuteSqlRawAsync(
        """
        CREATE TABLE IF NOT EXISTS "Suppliers" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "Name" text NOT NULL,
            "ContactName" text NOT NULL DEFAULT '',
            "Phone" text NOT NULL DEFAULT '',
            "Email" text NOT NULL DEFAULT '',
            "IsActive" boolean NOT NULL DEFAULT true
        );

        CREATE TABLE IF NOT EXISTS "Branches" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "Code" text NOT NULL,
            "Name" text NOT NULL,
            "Address" text NOT NULL,
            "IsActive" boolean NOT NULL DEFAULT true
        );

        CREATE TABLE IF NOT EXISTS "UserBranchAccesses" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "UserId" integer NOT NULL,
            "BranchId" integer NOT NULL
        );

        CREATE TABLE IF NOT EXISTS "PermissionProfiles" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "Name" text NOT NULL,
            "ModulePermissions" text NOT NULL,
            "IsAdmin" boolean NOT NULL DEFAULT false,
            "IsActive" boolean NOT NULL DEFAULT true
        );

        CREATE TABLE IF NOT EXISTS "AuditLogs" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "CreatedAt" timestamp with time zone NOT NULL,
            "Action" text NOT NULL,
            "Entity" text NOT NULL,
            "EntityId" integer NULL,
            "BranchId" integer NULL,
            "Username" text NOT NULL DEFAULT '',
            "IpAddress" text NOT NULL DEFAULT '',
            "Details" text NOT NULL DEFAULT ''
        );

        CREATE TABLE IF NOT EXISTS "ProductStocks" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "ProductId" integer NOT NULL,
            "BranchId" integer NOT NULL,
            "Stock" integer NOT NULL DEFAULT 0,
            "MinStock" integer NOT NULL DEFAULT 5
        );

        CREATE TABLE IF NOT EXISTS "StockTransfers" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "ProductId" integer NOT NULL,
            "FromBranchId" integer NOT NULL,
            "FromWarehouseId" integer NULL,
            "ToBranchId" integer NOT NULL,
            "ToWarehouseId" integer NULL,
            "Quantity" integer NOT NULL DEFAULT 0,
            "Notes" text NOT NULL DEFAULT '',
            "UserId" integer NULL,
            "CreatedAt" timestamp with time zone NOT NULL
        );

        CREATE TABLE IF NOT EXISTS "ProductLots" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "ProductId" integer NOT NULL,
            "BranchId" integer NOT NULL,
            "LotNumber" text NOT NULL DEFAULT '',
            "SerialNumber" text NULL,
            "ExpirationDate" timestamp with time zone NULL,
            "Quantity" integer NOT NULL DEFAULT 0,
            "UnitCost" numeric(18,2) NOT NULL DEFAULT 0,
            "CreatedAt" timestamp with time zone NOT NULL,
            "UpdatedAt" timestamp with time zone NOT NULL
        );

        CREATE TABLE IF NOT EXISTS "PromotionRules" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "Name" text NOT NULL,
            "IsActive" boolean NOT NULL DEFAULT true,
            "RuleType" text NOT NULL DEFAULT 'ThreeForTwo',
            "BranchId" integer NULL,
            "ProductId" integer NULL,
            "ProductIdsCsv" text NULL,
            "ComboPrice" numeric(18,2) NOT NULL DEFAULT 0,
            "BuyQty" integer NOT NULL DEFAULT 3,
            "PayQty" integer NOT NULL DEFAULT 2,
            "DiscountPercent" numeric(18,2) NOT NULL DEFAULT 0,
            "StartTime" time without time zone NULL,
            "EndTime" time without time zone NULL,
            "DaysOfWeekCsv" text NULL,
            "CreatedAt" timestamp with time zone NOT NULL
        );

        CREATE TABLE IF NOT EXISTS "CfdiDocuments" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "SaleId" integer NOT NULL,
            "PacProvider" text NOT NULL DEFAULT '',
            "Status" text NOT NULL DEFAULT 'Draft',
            "Uuid" text NULL,
            "XmlPath" text NULL,
            "PdfPath" text NULL,
            "ErrorMessage" text NULL,
            "CreatedAt" timestamp with time zone NOT NULL,
            "StampedAt" timestamp with time zone NULL,
            "CancelledAt" timestamp with time zone NULL
        );

        CREATE TABLE IF NOT EXISTS "AccountingClosures" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "BranchId" integer NOT NULL,
            "ClosureDate" timestamp with time zone NOT NULL,
            "Status" text NOT NULL DEFAULT 'Closed',
            "ClosedByUserId" integer NOT NULL,
            "ClosedAt" timestamp with time zone NOT NULL,
            "Notes" text NOT NULL DEFAULT '',
            "ReopenedByUserId" integer NULL,
            "ReopenedAt" timestamp with time zone NULL,
            "ReopenReason" text NULL
        );

        CREATE TABLE IF NOT EXISTS "Warehouses" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "BranchId" integer NOT NULL,
            "Code" text NOT NULL,
            "Name" text NOT NULL,
            "IsActive" boolean NOT NULL DEFAULT true
        );

        CREATE TABLE IF NOT EXISTS "WarehouseStocks" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "WarehouseId" integer NOT NULL,
            "ProductId" integer NOT NULL,
            "Stock" integer NOT NULL DEFAULT 0,
            "MinStock" integer NOT NULL DEFAULT 5
        );

        CREATE TABLE IF NOT EXISTS "PriceLists" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "Name" text NOT NULL,
            "IsActive" boolean NOT NULL DEFAULT true,
            "IsWholesale" boolean NOT NULL DEFAULT false
        );

        CREATE TABLE IF NOT EXISTS "PriceListItems" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "PriceListId" integer NOT NULL,
            "ProductId" integer NOT NULL,
            "MinQty" integer NOT NULL DEFAULT 1,
            "Price" numeric(18,2) NOT NULL DEFAULT 0
        );

        CREATE TABLE IF NOT EXISTS "Tenants" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "Name" text NOT NULL,
            "Code" text NOT NULL,
            "SchemaName" text NOT NULL,
            "Host" text NULL,
            "IsActive" boolean NOT NULL DEFAULT true,
            "CreatedAt" timestamp with time zone NOT NULL
        );

        CREATE TABLE IF NOT EXISTS "AppTelemetryEvents" (
            "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "CreatedAt" timestamp with time zone NOT NULL,
            "Path" text NOT NULL DEFAULT '',
            "Method" text NOT NULL DEFAULT '',
            "StatusCode" integer NOT NULL DEFAULT 200,
            "DurationMs" bigint NOT NULL DEFAULT 0,
            "IpAddress" text NOT NULL DEFAULT '',
            "Username" text NULL,
            "Error" text NULL
        );

        CREATE TABLE IF NOT EXISTS "CfdiVaultFiles" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "SaleId" integer NOT NULL,
            "DocumentType" text NOT NULL DEFAULT 'XML',
            "OriginalFileName" text NOT NULL DEFAULT '',
            "StoragePath" text NOT NULL DEFAULT '',
            "Sha256" text NOT NULL DEFAULT '',
            "SizeBytes" bigint NOT NULL DEFAULT 0,
            "CreatedAt" timestamp with time zone NOT NULL
        );

        CREATE TABLE IF NOT EXISTS "ReplenishmentRules" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "BranchId" integer NOT NULL,
            "WarehouseId" integer NOT NULL,
            "ProductId" integer NOT NULL,
            "MinLevel" integer NOT NULL DEFAULT 0,
            "MaxLevel" integer NOT NULL DEFAULT 0,
            "SuggestedOrderQty" integer NOT NULL DEFAULT 0,
            "AutoEnabled" boolean NOT NULL DEFAULT true,
            "UpdatedAt" timestamp with time zone NOT NULL
        );

        CREATE TABLE IF NOT EXISTS "CycleCounts" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "BranchId" integer NOT NULL,
            "WarehouseId" integer NOT NULL,
            "CreatedByUserId" integer NOT NULL,
            "AuthorizedByUserId" integer NULL,
            "Status" text NOT NULL DEFAULT 'Open',
            "Notes" text NOT NULL DEFAULT '',
            "CreatedAt" timestamp with time zone NOT NULL,
            "AuthorizedAt" timestamp with time zone NULL
        );

        CREATE TABLE IF NOT EXISTS "CycleCountLines" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "CycleCountId" integer NOT NULL,
            "ProductId" integer NOT NULL,
            "SystemQty" integer NOT NULL DEFAULT 0,
            "CountedQty" integer NOT NULL DEFAULT 0
        );

        CREATE TABLE IF NOT EXISTS "LotTraces" (
            "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "SaleId" integer NULL,
            "ProductId" integer NOT NULL,
            "ProductLotId" integer NULL,
            "BranchId" integer NOT NULL,
            "Quantity" integer NOT NULL DEFAULT 0,
            "MovementType" text NOT NULL DEFAULT 'Sale',
            "Reference" text NOT NULL DEFAULT '',
            "CreatedAt" timestamp with time zone NOT NULL
        );

        CREATE TABLE IF NOT EXISTS "SaleReturns" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "SaleId" integer NOT NULL,
            "BranchId" integer NOT NULL,
            "CreatedByUserId" integer NOT NULL,
            "AuthorizedByUserId" integer NULL,
            "AppliedByUserId" integer NULL,
            "Reason" text NOT NULL DEFAULT '',
            "Status" text NOT NULL DEFAULT 'Requested',
            "RequestedSignature" text NOT NULL DEFAULT '',
            "SupervisorSignature" text NULL,
            "SupervisorSignatureHash" text NULL,
            "CreatedAt" timestamp with time zone NOT NULL,
            "ApprovedAt" timestamp with time zone NULL,
            "AppliedAt" timestamp with time zone NULL,
            "TotalReturned" numeric(18,2) NOT NULL DEFAULT 0
        );

        CREATE TABLE IF NOT EXISTS "SaleReturnLines" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "SaleReturnId" integer NOT NULL,
            "SaleDetailId" integer NOT NULL,
            "Quantity" integer NOT NULL DEFAULT 0,
            "UnitPrice" numeric(18,2) NOT NULL DEFAULT 0
        );

        CREATE TABLE IF NOT EXISTS "CashShifts" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "BranchId" integer NOT NULL,
            "UserId" integer NOT NULL,
            "OpenedAt" timestamp with time zone NOT NULL,
            "OpeningFloat" numeric(18,2) NOT NULL DEFAULT 0,
            "ClosedAt" timestamp with time zone NULL,
            "ClosingDeclared" numeric(18,2) NULL,
            "SystemCashTotal" numeric(18,2) NULL,
            "Difference" numeric(18,2) NULL,
            "Status" text NOT NULL DEFAULT 'Open'
        );
        ALTER TABLE "CashShifts" ADD COLUMN IF NOT EXISTS "ClosingSignature" text NOT NULL DEFAULT '';
        ALTER TABLE "CashShifts" ADD COLUMN IF NOT EXISTS "ClosingNotes" text NOT NULL DEFAULT '';
        ALTER TABLE "CashShifts" ADD COLUMN IF NOT EXISTS "ClosingEvidencePath" text NULL;

        ALTER TABLE "Products" ADD COLUMN IF NOT EXISTS "ProductNumber" integer NOT NULL DEFAULT 0;
        ALTER TABLE "Products" ADD COLUMN IF NOT EXISTS "PriceIncludesTax" boolean NOT NULL DEFAULT false;
        ALTER TABLE "Products" ADD COLUMN IF NOT EXISTS "PromotionType" text NOT NULL DEFAULT 'None';
        ALTER TABLE "Products" ADD COLUMN IF NOT EXISTS "PromotionValue" numeric(18,2) NOT NULL DEFAULT 0;
        ALTER TABLE "Products" ADD COLUMN IF NOT EXISTS "PromotionMinQty" integer NOT NULL DEFAULT 0;

        ALTER TABLE "Sales" ADD COLUMN IF NOT EXISTS "BranchId" integer NOT NULL DEFAULT 1;
        ALTER TABLE "Sales" ADD COLUMN IF NOT EXISTS "SubtotalAmount" numeric(18,2) NOT NULL DEFAULT 0;
        ALTER TABLE "Sales" ADD COLUMN IF NOT EXISTS "TaxAmount" numeric(18,2) NOT NULL DEFAULT 0;
        ALTER TABLE "Sales" ADD COLUMN IF NOT EXISTS "DiscountAmount" numeric(18,2) NOT NULL DEFAULT 0;
        ALTER TABLE "Sales" ADD COLUMN IF NOT EXISTS "PaymentMethod" text NOT NULL DEFAULT 'Cash';
        ALTER TABLE "Sales" ADD COLUMN IF NOT EXISTS "AuthorizationCode" text NULL;
        ALTER TABLE "Sales" ADD COLUMN IF NOT EXISTS "PricesIncludeTax" boolean NOT NULL DEFAULT false;
        ALTER TABLE "Sales" ADD COLUMN IF NOT EXISTS "AmountReceived" numeric(18,2) NOT NULL DEFAULT 0;
        ALTER TABLE "Sales" ADD COLUMN IF NOT EXISTS "ChangeAmount" numeric(18,2) NOT NULL DEFAULT 0;
        ALTER TABLE "Sales" ADD COLUMN IF NOT EXISTS "CancelledAt" timestamp with time zone NULL;
        ALTER TABLE "Sales" ADD COLUMN IF NOT EXISTS "CancelReason" text NULL;
        ALTER TABLE "Sales" ADD COLUMN IF NOT EXISTS "CfdiStatus" text NOT NULL DEFAULT 'NoAplica';
        ALTER TABLE "Sales" ADD COLUMN IF NOT EXISTS "CfdiUuid" text NULL;
        ALTER TABLE "Sales" ADD COLUMN IF NOT EXISTS "WarehouseId" integer NULL;

        ALTER TABLE "SaleDetails" ADD COLUMN IF NOT EXISTS "DiscountPercent" numeric(18,2) NOT NULL DEFAULT 0;
        ALTER TABLE "SaleDetails" ADD COLUMN IF NOT EXISTS "DiscountAmount" numeric(18,2) NOT NULL DEFAULT 0;

        ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "ModulePermissions" text NOT NULL DEFAULT 'dashboard,sales,products,customers,expenses,cashcuts,supplierorders,reports,cashshifts';
        ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "PermissionProfileId" integer NULL;
        ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "TenantId" integer NULL;
        ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "IsSuperUser" boolean NOT NULL DEFAULT false;

        ALTER TABLE "AppConfigs" ADD COLUMN IF NOT EXISTS "CurrencySymbol" text NOT NULL DEFAULT '$';
        ALTER TABLE "AppConfigs" ADD COLUMN IF NOT EXISTS "TaxRate" numeric(18,2) NOT NULL DEFAULT 16;
        ALTER TABLE "AppConfigs" ADD COLUMN IF NOT EXISTS "TicketPrinterName" text NULL;
        ALTER TABLE "AppConfigs" ADD COLUMN IF NOT EXISTS "CerPath" text NULL;
        ALTER TABLE "AppConfigs" ADD COLUMN IF NOT EXISTS "KeyPath" text NULL;
        ALTER TABLE "AppConfigs" ADD COLUMN IF NOT EXISTS "PrivateKeyPassword" text NULL;
        ALTER TABLE "AppConfigs" ADD COLUMN IF NOT EXISTS "Street" text NULL;
        ALTER TABLE "AppConfigs" ADD COLUMN IF NOT EXISTS "PostalCode" text NULL;
        ALTER TABLE "AppConfigs" ADD COLUMN IF NOT EXISTS "State" text NULL;
        ALTER TABLE "AppConfigs" ADD COLUMN IF NOT EXISTS "Country" text NULL DEFAULT 'Mexico';
        ALTER TABLE "AppConfigs" ADD COLUMN IF NOT EXISTS "PacProvider" text NULL;
        ALTER TABLE "AppConfigs" ADD COLUMN IF NOT EXISTS "PacApiUrl" text NULL;
        ALTER TABLE "AppConfigs" ADD COLUMN IF NOT EXISTS "PacApiKey" text NULL;
        ALTER TABLE "AppConfigs" ADD COLUMN IF NOT EXISTS "PacApiSecret" text NULL;
        ALTER TABLE "AppConfigs" ADD COLUMN IF NOT EXISTS "PacTestMode" boolean NOT NULL DEFAULT true;

        ALTER TABLE "CashCuts" ADD COLUMN IF NOT EXISTS "BranchId" integer NOT NULL DEFAULT 1;
        ALTER TABLE "CashCuts" ADD COLUMN IF NOT EXISTS "CashSales" numeric(18,2) NOT NULL DEFAULT 0;
        ALTER TABLE "CashCuts" ADD COLUMN IF NOT EXISTS "CardSales" numeric(18,2) NOT NULL DEFAULT 0;
        ALTER TABLE "CashCuts" ADD COLUMN IF NOT EXISTS "TransferSales" numeric(18,2) NOT NULL DEFAULT 0;

        ALTER TABLE "SupplierOrders" ADD COLUMN IF NOT EXISTS "SupplierId" integer NOT NULL DEFAULT 1;
        ALTER TABLE "SupplierOrders" ADD COLUMN IF NOT EXISTS "ProductId" integer NOT NULL DEFAULT 1;
        ALTER TABLE "SupplierOrders" ADD COLUMN IF NOT EXISTS "BranchId" integer NOT NULL DEFAULT 1;
        ALTER TABLE "SupplierOrders" ADD COLUMN IF NOT EXISTS "WarehouseId" integer NULL;
        ALTER TABLE "SupplierOrders" ADD COLUMN IF NOT EXISTS "UnitCost" numeric(18,2) NOT NULL DEFAULT 0;

        ALTER TABLE "Customers" ADD COLUMN IF NOT EXISTS "CfdiUse" text NOT NULL DEFAULT 'G03';
        ALTER TABLE "Customers" ADD COLUMN IF NOT EXISTS "FiscalRegime" text NOT NULL DEFAULT '601';
        ALTER TABLE "Customers" ADD COLUMN IF NOT EXISTS "InvoiceType" text NOT NULL DEFAULT 'I';
        ALTER TABLE "Customers" ADD COLUMN IF NOT EXISTS "PaymentForm" text NOT NULL DEFAULT '01';
        ALTER TABLE "Customers" ADD COLUMN IF NOT EXISTS "PaymentMethodSat" text NOT NULL DEFAULT 'PUE';
        ALTER TABLE "Customers" ADD COLUMN IF NOT EXISTS "PriceListId" integer NULL;

        ALTER TABLE "AppConfigs" ADD COLUMN IF NOT EXISTS "SmtpHost" text NULL;
        ALTER TABLE "AppConfigs" ADD COLUMN IF NOT EXISTS "SmtpPort" integer NOT NULL DEFAULT 587;
        ALTER TABLE "AppConfigs" ADD COLUMN IF NOT EXISTS "SmtpUseSsl" boolean NOT NULL DEFAULT true;
        ALTER TABLE "AppConfigs" ADD COLUMN IF NOT EXISTS "SmtpUser" text NULL;
        ALTER TABLE "AppConfigs" ADD COLUMN IF NOT EXISTS "SmtpPassword" text NULL;
        ALTER TABLE "AppConfigs" ADD COLUMN IF NOT EXISTS "AlertFromEmail" text NULL;
        ALTER TABLE "AppConfigs" ADD COLUMN IF NOT EXISTS "AlertToEmails" text NULL;

        ALTER TABLE "SaleReturns" ADD COLUMN IF NOT EXISTS "AppliedByUserId" integer NULL;
        ALTER TABLE "SaleReturns" ADD COLUMN IF NOT EXISTS "Status" text NOT NULL DEFAULT 'Requested';
        ALTER TABLE "SaleReturns" ADD COLUMN IF NOT EXISTS "RequestedSignature" text NOT NULL DEFAULT '';
        ALTER TABLE "SaleReturns" ADD COLUMN IF NOT EXISTS "SupervisorSignature" text NULL;
        ALTER TABLE "SaleReturns" ADD COLUMN IF NOT EXISTS "SupervisorSignatureHash" text NULL;
        ALTER TABLE "SaleReturns" ADD COLUMN IF NOT EXISTS "ApprovedAt" timestamp with time zone NULL;
        ALTER TABLE "SaleReturns" ADD COLUMN IF NOT EXISTS "AppliedAt" timestamp with time zone NULL;
        ALTER TABLE "SaleReturns" ALTER COLUMN "AuthorizedByUserId" DROP NOT NULL;

        ALTER TABLE "AppConfigs" ADD COLUMN IF NOT EXISTS "SalesAccount" text NOT NULL DEFAULT '4000-000-000';
        ALTER TABLE "AppConfigs" ADD COLUMN IF NOT EXISTS "VatAccount" text NOT NULL DEFAULT '2080-000-000';
        ALTER TABLE "AppConfigs" ADD COLUMN IF NOT EXISTS "CashAccount" text NOT NULL DEFAULT '1010-000-000';
        ALTER TABLE "AppConfigs" ADD COLUMN IF NOT EXISTS "CardAccount" text NOT NULL DEFAULT '1020-000-000';
        ALTER TABLE "AppConfigs" ADD COLUMN IF NOT EXISTS "TransferAccount" text NOT NULL DEFAULT '1030-000-000';

        ALTER TABLE "StockTransfers" ADD COLUMN IF NOT EXISTS "FromWarehouseId" integer NULL;
        ALTER TABLE "StockTransfers" ADD COLUMN IF NOT EXISTS "ToWarehouseId" integer NULL;

        CREATE UNIQUE INDEX IF NOT EXISTS "IX_UserBranchAccesses_User_Branch" ON "UserBranchAccesses" ("UserId", "BranchId");
        CREATE UNIQUE INDEX IF NOT EXISTS "IX_ProductStocks_Product_Branch" ON "ProductStocks" ("ProductId", "BranchId");
        CREATE UNIQUE INDEX IF NOT EXISTS "IX_CfdiDocuments_SaleId" ON "CfdiDocuments" ("SaleId");
        CREATE INDEX IF NOT EXISTS "IX_ProductLots_Branch_Product_Lot" ON "ProductLots" ("BranchId", "ProductId", "LotNumber");
        CREATE UNIQUE INDEX IF NOT EXISTS "IX_Warehouses_Branch_Code" ON "Warehouses" ("BranchId", "Code");
        CREATE UNIQUE INDEX IF NOT EXISTS "IX_WarehouseStocks_Warehouse_Product" ON "WarehouseStocks" ("WarehouseId", "ProductId");
        CREATE UNIQUE INDEX IF NOT EXISTS "IX_PriceListItems_List_Product_Min" ON "PriceListItems" ("PriceListId", "ProductId", "MinQty");
        CREATE UNIQUE INDEX IF NOT EXISTS "IX_Tenants_Code" ON "Tenants" ("Code");
        CREATE UNIQUE INDEX IF NOT EXISTS "IX_Tenants_SchemaName" ON "Tenants" ("SchemaName");
        CREATE INDEX IF NOT EXISTS "IX_AppTelemetryEvents_CreatedAt" ON "AppTelemetryEvents" ("CreatedAt");
        CREATE INDEX IF NOT EXISTS "IX_CfdiVaultFiles_Sale_Doc_CreatedAt" ON "CfdiVaultFiles" ("SaleId", "DocumentType", "CreatedAt");
        CREATE UNIQUE INDEX IF NOT EXISTS "IX_ReplenishmentRules_BWP" ON "ReplenishmentRules" ("BranchId", "WarehouseId", "ProductId");
        CREATE UNIQUE INDEX IF NOT EXISTS "IX_CycleCountLines_Cycle_Product" ON "CycleCountLines" ("CycleCountId", "ProductId");
        CREATE INDEX IF NOT EXISTS "IX_LotTraces_Sale_Product_CreatedAt" ON "LotTraces" ("SaleId", "ProductId", "CreatedAt");
        CREATE INDEX IF NOT EXISTS "IX_SaleReturnLines_Return_Detail" ON "SaleReturnLines" ("SaleReturnId", "SaleDetailId");

        INSERT INTO "Branches" ("Code", "Name", "Address", "IsActive")
        SELECT 'MATRIZ', 'Sucursal Matriz', 'Pendiente por configurar', true
        WHERE NOT EXISTS (SELECT 1 FROM "Branches");

        INSERT INTO "Suppliers" ("Name", "ContactName", "Phone", "Email", "IsActive")
        SELECT 'Proveedor General', '', '', '', true
        WHERE NOT EXISTS (SELECT 1 FROM "Suppliers");

        INSERT INTO "PriceLists" ("Name", "IsActive", "IsWholesale")
        SELECT 'Mostrador', true, false
        WHERE NOT EXISTS (SELECT 1 FROM "PriceLists" WHERE "Name" = 'Mostrador');

        INSERT INTO "PriceLists" ("Name", "IsActive", "IsWholesale")
        SELECT 'Mayoreo', true, true
        WHERE NOT EXISTS (SELECT 1 FROM "PriceLists" WHERE "Name" = 'Mayoreo');

        INSERT INTO "Warehouses" ("BranchId", "Code", "Name", "IsActive")
        SELECT b."Id", 'PRINCIPAL', 'Almacén Principal', true
        FROM "Branches" b
        WHERE NOT EXISTS (
            SELECT 1 FROM "Warehouses" w WHERE w."BranchId" = b."Id" AND w."Code" = 'PRINCIPAL'
        );

        INSERT INTO "WarehouseStocks" ("WarehouseId", "ProductId", "Stock", "MinStock")
        SELECT w."Id", ps."ProductId", ps."Stock", ps."MinStock"
        FROM "ProductStocks" ps
        JOIN "Warehouses" w ON w."BranchId" = ps."BranchId" AND w."Code" = 'PRINCIPAL'
        WHERE NOT EXISTS (
            SELECT 1 FROM "WarehouseStocks" ws WHERE ws."WarehouseId" = w."Id" AND ws."ProductId" = ps."ProductId"
        );

        INSERT INTO "PermissionProfiles" ("Name", "ModulePermissions", "IsAdmin", "IsActive")
        SELECT 'Administrador', 'dashboard,sales,products,customers,expenses,cashcuts,cashshifts,supplierorders,reports,config,users,branches', true, true
        WHERE NOT EXISTS (SELECT 1 FROM "PermissionProfiles" WHERE "Name" = 'Administrador');

        INSERT INTO "PermissionProfiles" ("Name", "ModulePermissions", "IsAdmin", "IsActive")
        SELECT 'Caja', 'dashboard,sales,customers,cashcuts,cashshifts', false, true
        WHERE NOT EXISTS (SELECT 1 FROM "PermissionProfiles" WHERE "Name" = 'Caja');

        INSERT INTO "Tenants" ("Name", "Code", "SchemaName", "Host", "IsActive", "CreatedAt")
        SELECT 'Tenant Principal', 'principal', 'public', NULL, true, NOW()
        WHERE NOT EXISTS (SELECT 1 FROM "Tenants" WHERE "SchemaName" = 'public');
        """);

    // Normaliza consecutivo para evitar duplicados previos (incluyendo ceros) y luego crea índice único.
    await db.Database.ExecuteSqlRawAsync(
        """
        WITH renumbered AS (
            SELECT
                "Id",
                ROW_NUMBER() OVER (
                    ORDER BY
                        CASE WHEN "ProductNumber" IS NULL OR "ProductNumber" = 0 THEN 1 ELSE 0 END,
                        "ProductNumber",
                        "Id"
                ) AS rn
            FROM "Products"
        )
        UPDATE "Products" p
        SET "ProductNumber" = r.rn
        FROM renumbered r
        WHERE p."Id" = r."Id";

        CREATE UNIQUE INDEX IF NOT EXISTS "IX_Products_ProductNumber" ON "Products" ("ProductNumber");
        """);

    if (!await db.Users.AnyAsync(u => u.Username == "admin"))
    {
        var principalTenantId = await db.Tenants
            .Where(t => t.SchemaName == "public")
            .Select(t => (int?)t.Id)
            .FirstOrDefaultAsync();
        db.Users.Add(new User
        {
            Username = "admin",
            PasswordHash = BCrypt.Net.BCrypt.HashPassword("admin123"),
            FullName = "Administrador",
            Role = "SuperUser",
            IsSuperUser = true,
            TenantId = principalTenantId,
            ModulePermissions = string.Join(',', ModuleCatalog.All),
            IsActive = true
        });
        await db.SaveChangesAsync();
    }

    var admin = await db.Users.FirstOrDefaultAsync(u => u.Username == "admin");
    var branch = await db.Branches.OrderBy(b => b.Id).FirstOrDefaultAsync();

    if (admin is not null)
    {
        admin.Role = "SuperUser";
        admin.IsSuperUser = true;
        admin.TenantId ??= await db.Tenants
            .Where(t => t.SchemaName == "public")
            .Select(t => (int?)t.Id)
            .FirstOrDefaultAsync();
        admin.ModulePermissions = string.Join(',', ModuleCatalog.All);
        admin.PermissionProfileId ??= await db.PermissionProfiles
            .Where(p => p.IsAdmin)
            .OrderBy(p => p.Id)
            .Select(p => (int?)p.Id)
            .FirstOrDefaultAsync();

        if (branch is not null)
        {
            var hasAccess = await db.UserBranchAccesses.AnyAsync(x => x.UserId == admin.Id && x.BranchId == branch.Id);
            if (!hasAccess)
            {
                db.UserBranchAccesses.Add(new UserBranchAccess { UserId = admin.Id, BranchId = branch.Id });
            }
        }

        await db.SaveChangesAsync();
    }

    var principalTenantIdForUsers = await db.Tenants
        .Where(t => t.SchemaName == "public")
        .Select(t => (int?)t.Id)
        .FirstOrDefaultAsync();
    if (principalTenantIdForUsers.HasValue)
    {
        var usersWithoutTenant = await db.Users
            .Where(u => !u.IsSuperUser && u.TenantId == null)
            .ToListAsync();
        foreach (var u in usersWithoutTenant)
        {
            u.TenantId = principalTenantIdForUsers.Value;
        }
        if (usersWithoutTenant.Count > 0)
        {
            await db.SaveChangesAsync();
        }
    }
}

if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Error");
    app.UseHsts();
}

app.UseForwardedHeaders();
app.UseHttpsRedirection();
app.UseStaticFiles();
app.UseRouting();
app.UseAuthentication();

app.Use(async (ctx, next) =>
{
    static string SanitizeSchema(string? raw)
    {
        if (string.IsNullOrWhiteSpace(raw))
        {
            return "public";
        }

        var clean = raw.Trim().ToLowerInvariant();
        return System.Text.RegularExpressions.Regex.IsMatch(clean, "^[a-z_][a-z0-9_]{0,62}$")
            ? clean
            : "public";
    }

    var schema = "public";
    if (ctx.User.Identity?.IsAuthenticated == true)
    {
        schema = SanitizeSchema(ctx.User.FindFirst("tenant_schema")?.Value);
    }
    else
    {
        var host = (ctx.Request.Host.Host ?? string.Empty).ToLowerInvariant();
        if (!string.IsNullOrWhiteSpace(host))
        {
            try
            {
                using var scope = app.Services.CreateScope();
                var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();
                var fromHost = await db.Tenants
                    .Where(t => t.IsActive && t.Host != null && t.Host.ToLower() == host)
                    .Select(t => t.SchemaName)
                    .FirstOrDefaultAsync();
                schema = SanitizeSchema(fromHost);
            }
            catch
            {
                schema = "public";
            }
        }
    }

    try
    {
        var db = ctx.RequestServices.GetRequiredService<AppDbContext>();
        await db.Database.ExecuteSqlRawAsync($"SET search_path TO \"{schema}\", public;");
    }
    catch
    {
        // Si no se puede fijar tenant, mantener flujo para no bloquear login o estáticos.
    }

    await next();
});

app.UseAuthorization();

app.Use(async (ctx, next) =>
{
    var path = ctx.Request.Path.Value ?? "/";
    var skipTelemetry =
        path.StartsWith("/css", StringComparison.OrdinalIgnoreCase) ||
        path.StartsWith("/js", StringComparison.OrdinalIgnoreCase) ||
        path.StartsWith("/lib", StringComparison.OrdinalIgnoreCase) ||
        path.StartsWith("/uploads", StringComparison.OrdinalIgnoreCase) ||
        path.StartsWith("/favicon", StringComparison.OrdinalIgnoreCase);

    if (skipTelemetry)
    {
        await next();
        return;
    }

    var sw = System.Diagnostics.Stopwatch.StartNew();
    string? error = null;
    try
    {
        await next();
    }
    catch (Exception ex)
    {
        error = ex.GetType().Name;
        throw;
    }
    finally
    {
        sw.Stop();
        var duration = sw.ElapsedMilliseconds;
        var status = ctx.Response.StatusCode;
        if (duration >= 1200 || status >= 500 || !string.IsNullOrWhiteSpace(error))
        {
            try
            {
                using var scope = app.Services.CreateScope();
                var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();
                var email = scope.ServiceProvider.GetRequiredService<IAlertEmailService>();
                db.AppTelemetryEvents.Add(new AppTelemetryEvent
                {
                    CreatedAt = DateTime.UtcNow,
                    Path = path,
                    Method = ctx.Request.Method,
                    StatusCode = status,
                    DurationMs = duration,
                    IpAddress = ClientIpResolver.Get(ctx),
                    Username = ctx.User.Identity?.IsAuthenticated == true ? ctx.User.Identity?.Name : null,
                    Error = error
                });
                await db.SaveChangesAsync();

                var mustAlert = status >= 500 || duration >= 3000 || !string.IsNullOrWhiteSpace(error);
                if (mustAlert)
                {
                    var canSend = false;
                    lock (alertSync)
                    {
                        if ((DateTime.UtcNow - lastAlertUtc).TotalMinutes >= 5)
                        {
                            canSend = true;
                            lastAlertUtc = DateTime.UtcNow;
                        }
                    }

                    if (canSend)
                    {
                        var subject = $"[HN Nexus POS] Alerta {(status >= 500 ? "ERROR" : "LATENCIA")} {status} {path}";
                        var body = $"""
Fecha UTC: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss}
Ruta: {ctx.Request.Method} {path}
Status: {status}
Duración: {duration} ms
Usuario: {ctx.User.Identity?.Name ?? "-"}
IP: {ClientIpResolver.Get(ctx)}
Error: {error ?? "-"}
""";
                        _ = await email.SendAlertAsync(subject, body);
                    }
                }
            }
            catch
            {
                // No romper request por fallo de telemetría.
            }
        }
    }
});

app.Use(async (ctx, next) =>
{
    if (ctx.User.Identity?.IsAuthenticated == true && !ctx.User.IsInRole("Admin"))
    {
        var path = ctx.Request.Path.Value ?? "/";
        var route = moduleRoutes
            .OrderByDescending(x => x.Key.Length)
            .FirstOrDefault(x => path.StartsWith(x.Key, StringComparison.OrdinalIgnoreCase));

        if (!string.IsNullOrWhiteSpace(route.Key))
        {
            var modules = (ctx.User.FindFirstValue("modules") ?? string.Empty)
                .Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
                .Select(x => x.ToLowerInvariant())
                .ToHashSet();

            if (!modules.Contains(route.Value))
            {
                ctx.Response.Redirect("/Account/Denied");
                return;
            }
        }
    }

    await next();
});

app.MapRazorPages();

app.Run();
