using System.Globalization;
using System.Security.Claims;
using HN_Nexus.WebPOS.Data;
using HN_Nexus.WebPOS.Models;
using HN_Nexus.WebPOS.Services;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.EntityFrameworkCore;
using QuestPDF.Infrastructure;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddDbContext<AppDbContext>(opt =>
    opt.UseNpgsql(builder.Configuration.GetConnectionString("Default")));

builder.Services.AddHttpContextAccessor();
builder.Services.AddScoped<IModuleAccessService, ModuleAccessService>();
builder.Services.AddScoped<IUserContextService, UserContextService>();
builder.Services.AddScoped<IReportPdfService, ReportPdfService>();

builder.Services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme)
    .AddCookie(options =>
    {
        options.LoginPath = "/Account/Login";
        options.AccessDeniedPath = "/Account/Denied";
        options.Cookie.Name = "HNNexus.WebPOS.Auth";
        options.SlidingExpiration = true;
        options.ExpireTimeSpan = TimeSpan.FromHours(8);
    });

builder.Services.AddAuthorization(options =>
{
    options.AddPolicy("AdminOnly", policy => policy.RequireClaim(ClaimTypes.Role, "Admin"));
});

builder.Services.AddRazorPages(options =>
{
    options.Conventions.AuthorizeFolder("/");
    options.Conventions.AllowAnonymousToFolder("/Account");
    options.Conventions.AuthorizeFolder("/Config", "AdminOnly");
});

var moduleRoutes = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
{
    ["/"] = ModuleCatalog.Dashboard,
    ["/Index"] = ModuleCatalog.Dashboard,
    ["/Sales"] = ModuleCatalog.Sales,
    ["/Products"] = ModuleCatalog.Products,
    ["/Customers"] = ModuleCatalog.Customers,
    ["/Expenses"] = ModuleCatalog.Expenses,
    ["/CashCuts"] = ModuleCatalog.CashCuts,
    ["/CashShifts"] = ModuleCatalog.CashShifts,
    ["/SupplierOrders"] = ModuleCatalog.SupplierOrders,
    ["/Reports"] = ModuleCatalog.Reports,
    ["/Inventory"] = ModuleCatalog.Products,
    ["/Config"] = ModuleCatalog.Config
};

var mx = new CultureInfo("es-MX");
CultureInfo.DefaultThreadCurrentCulture = mx;
CultureInfo.DefaultThreadCurrentUICulture = mx;

QuestPDF.Settings.License = LicenseType.Community;

var app = builder.Build();

using (var scope = app.Services.CreateScope())
{
    var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();
    await db.Database.EnsureCreatedAsync();

    await db.Database.ExecuteSqlRawAsync(
        """
        CREATE TABLE IF NOT EXISTS "Suppliers" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "Name" text NOT NULL,
            "ContactName" text NOT NULL DEFAULT '',
            "Phone" text NOT NULL DEFAULT '',
            "Email" text NOT NULL DEFAULT '',
            "IsActive" boolean NOT NULL DEFAULT true
        );

        CREATE TABLE IF NOT EXISTS "Branches" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "Code" text NOT NULL,
            "Name" text NOT NULL,
            "Address" text NOT NULL,
            "IsActive" boolean NOT NULL DEFAULT true
        );

        CREATE TABLE IF NOT EXISTS "UserBranchAccesses" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "UserId" integer NOT NULL,
            "BranchId" integer NOT NULL
        );

        CREATE TABLE IF NOT EXISTS "PermissionProfiles" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "Name" text NOT NULL,
            "ModulePermissions" text NOT NULL,
            "IsAdmin" boolean NOT NULL DEFAULT false,
            "IsActive" boolean NOT NULL DEFAULT true
        );

        CREATE TABLE IF NOT EXISTS "AuditLogs" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "CreatedAt" timestamp with time zone NOT NULL,
            "Action" text NOT NULL,
            "Entity" text NOT NULL,
            "EntityId" integer NULL,
            "BranchId" integer NULL,
            "Username" text NOT NULL DEFAULT '',
            "IpAddress" text NOT NULL DEFAULT '',
            "Details" text NOT NULL DEFAULT ''
        );

        CREATE TABLE IF NOT EXISTS "ProductStocks" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "ProductId" integer NOT NULL,
            "BranchId" integer NOT NULL,
            "Stock" integer NOT NULL DEFAULT 0,
            "MinStock" integer NOT NULL DEFAULT 5
        );

        CREATE TABLE IF NOT EXISTS "StockTransfers" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "ProductId" integer NOT NULL,
            "FromBranchId" integer NOT NULL,
            "ToBranchId" integer NOT NULL,
            "Quantity" integer NOT NULL DEFAULT 0,
            "Notes" text NOT NULL DEFAULT '',
            "UserId" integer NULL,
            "CreatedAt" timestamp with time zone NOT NULL
        );

        CREATE TABLE IF NOT EXISTS "CashShifts" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "BranchId" integer NOT NULL,
            "UserId" integer NOT NULL,
            "OpenedAt" timestamp with time zone NOT NULL,
            "OpeningFloat" numeric(18,2) NOT NULL DEFAULT 0,
            "ClosedAt" timestamp with time zone NULL,
            "ClosingDeclared" numeric(18,2) NULL,
            "SystemCashTotal" numeric(18,2) NULL,
            "Difference" numeric(18,2) NULL,
            "Status" text NOT NULL DEFAULT 'Open'
        );
        ALTER TABLE "CashShifts" ADD COLUMN IF NOT EXISTS "ClosingSignature" text NOT NULL DEFAULT '';
        ALTER TABLE "CashShifts" ADD COLUMN IF NOT EXISTS "ClosingNotes" text NOT NULL DEFAULT '';
        ALTER TABLE "CashShifts" ADD COLUMN IF NOT EXISTS "ClosingEvidencePath" text NULL;

        ALTER TABLE "Products" ADD COLUMN IF NOT EXISTS "ProductNumber" integer NOT NULL DEFAULT 0;
        ALTER TABLE "Products" ADD COLUMN IF NOT EXISTS "PriceIncludesTax" boolean NOT NULL DEFAULT false;
        ALTER TABLE "Products" ADD COLUMN IF NOT EXISTS "PromotionType" text NOT NULL DEFAULT 'None';
        ALTER TABLE "Products" ADD COLUMN IF NOT EXISTS "PromotionValue" numeric(18,2) NOT NULL DEFAULT 0;
        ALTER TABLE "Products" ADD COLUMN IF NOT EXISTS "PromotionMinQty" integer NOT NULL DEFAULT 0;

        ALTER TABLE "Sales" ADD COLUMN IF NOT EXISTS "BranchId" integer NOT NULL DEFAULT 1;
        ALTER TABLE "Sales" ADD COLUMN IF NOT EXISTS "SubtotalAmount" numeric(18,2) NOT NULL DEFAULT 0;
        ALTER TABLE "Sales" ADD COLUMN IF NOT EXISTS "TaxAmount" numeric(18,2) NOT NULL DEFAULT 0;
        ALTER TABLE "Sales" ADD COLUMN IF NOT EXISTS "DiscountAmount" numeric(18,2) NOT NULL DEFAULT 0;
        ALTER TABLE "Sales" ADD COLUMN IF NOT EXISTS "PaymentMethod" text NOT NULL DEFAULT 'Cash';
        ALTER TABLE "Sales" ADD COLUMN IF NOT EXISTS "AuthorizationCode" text NULL;
        ALTER TABLE "Sales" ADD COLUMN IF NOT EXISTS "PricesIncludeTax" boolean NOT NULL DEFAULT false;
        ALTER TABLE "Sales" ADD COLUMN IF NOT EXISTS "AmountReceived" numeric(18,2) NOT NULL DEFAULT 0;
        ALTER TABLE "Sales" ADD COLUMN IF NOT EXISTS "ChangeAmount" numeric(18,2) NOT NULL DEFAULT 0;
        ALTER TABLE "Sales" ADD COLUMN IF NOT EXISTS "CancelledAt" timestamp with time zone NULL;
        ALTER TABLE "Sales" ADD COLUMN IF NOT EXISTS "CancelReason" text NULL;

        ALTER TABLE "SaleDetails" ADD COLUMN IF NOT EXISTS "DiscountPercent" numeric(18,2) NOT NULL DEFAULT 0;
        ALTER TABLE "SaleDetails" ADD COLUMN IF NOT EXISTS "DiscountAmount" numeric(18,2) NOT NULL DEFAULT 0;

        ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "ModulePermissions" text NOT NULL DEFAULT 'dashboard,sales,products,customers,expenses,cashcuts,supplierorders,reports,cashshifts';
        ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "PermissionProfileId" integer NULL;

        ALTER TABLE "AppConfigs" ADD COLUMN IF NOT EXISTS "CurrencySymbol" text NOT NULL DEFAULT '$';
        ALTER TABLE "AppConfigs" ADD COLUMN IF NOT EXISTS "TaxRate" numeric(18,2) NOT NULL DEFAULT 16;
        ALTER TABLE "AppConfigs" ADD COLUMN IF NOT EXISTS "TicketPrinterName" text NULL;

        ALTER TABLE "CashCuts" ADD COLUMN IF NOT EXISTS "BranchId" integer NOT NULL DEFAULT 1;
        ALTER TABLE "CashCuts" ADD COLUMN IF NOT EXISTS "CashSales" numeric(18,2) NOT NULL DEFAULT 0;
        ALTER TABLE "CashCuts" ADD COLUMN IF NOT EXISTS "CardSales" numeric(18,2) NOT NULL DEFAULT 0;
        ALTER TABLE "CashCuts" ADD COLUMN IF NOT EXISTS "TransferSales" numeric(18,2) NOT NULL DEFAULT 0;

        ALTER TABLE "SupplierOrders" ADD COLUMN IF NOT EXISTS "SupplierId" integer NOT NULL DEFAULT 1;
        ALTER TABLE "SupplierOrders" ADD COLUMN IF NOT EXISTS "ProductId" integer NOT NULL DEFAULT 1;
        ALTER TABLE "SupplierOrders" ADD COLUMN IF NOT EXISTS "BranchId" integer NOT NULL DEFAULT 1;
        ALTER TABLE "SupplierOrders" ADD COLUMN IF NOT EXISTS "UnitCost" numeric(18,2) NOT NULL DEFAULT 0;

        ALTER TABLE "Customers" ADD COLUMN IF NOT EXISTS "CfdiUse" text NOT NULL DEFAULT 'G03';
        ALTER TABLE "Customers" ADD COLUMN IF NOT EXISTS "FiscalRegime" text NOT NULL DEFAULT '601';
        ALTER TABLE "Customers" ADD COLUMN IF NOT EXISTS "InvoiceType" text NOT NULL DEFAULT 'I';
        ALTER TABLE "Customers" ADD COLUMN IF NOT EXISTS "PaymentForm" text NOT NULL DEFAULT '01';
        ALTER TABLE "Customers" ADD COLUMN IF NOT EXISTS "PaymentMethodSat" text NOT NULL DEFAULT 'PUE';

        CREATE UNIQUE INDEX IF NOT EXISTS "IX_UserBranchAccesses_User_Branch" ON "UserBranchAccesses" ("UserId", "BranchId");
        CREATE UNIQUE INDEX IF NOT EXISTS "IX_ProductStocks_Product_Branch" ON "ProductStocks" ("ProductId", "BranchId");

        INSERT INTO "Branches" ("Code", "Name", "Address", "IsActive")
        SELECT 'MATRIZ', 'Sucursal Matriz', 'Pendiente por configurar', true
        WHERE NOT EXISTS (SELECT 1 FROM "Branches");

        INSERT INTO "Suppliers" ("Name", "ContactName", "Phone", "Email", "IsActive")
        SELECT 'Proveedor General', '', '', '', true
        WHERE NOT EXISTS (SELECT 1 FROM "Suppliers");

        INSERT INTO "PermissionProfiles" ("Name", "ModulePermissions", "IsAdmin", "IsActive")
        SELECT 'Administrador', 'dashboard,sales,products,customers,expenses,cashcuts,cashshifts,supplierorders,reports,config,users,branches', true, true
        WHERE NOT EXISTS (SELECT 1 FROM "PermissionProfiles" WHERE "Name" = 'Administrador');

        INSERT INTO "PermissionProfiles" ("Name", "ModulePermissions", "IsAdmin", "IsActive")
        SELECT 'Caja', 'dashboard,sales,customers,cashcuts,cashshifts', false, true
        WHERE NOT EXISTS (SELECT 1 FROM "PermissionProfiles" WHERE "Name" = 'Caja');
        """);

    // Normaliza consecutivo para evitar duplicados previos (incluyendo ceros) y luego crea índice único.
    await db.Database.ExecuteSqlRawAsync(
        """
        WITH renumbered AS (
            SELECT
                "Id",
                ROW_NUMBER() OVER (
                    ORDER BY
                        CASE WHEN "ProductNumber" IS NULL OR "ProductNumber" = 0 THEN 1 ELSE 0 END,
                        "ProductNumber",
                        "Id"
                ) AS rn
            FROM "Products"
        )
        UPDATE "Products" p
        SET "ProductNumber" = r.rn
        FROM renumbered r
        WHERE p."Id" = r."Id";

        CREATE UNIQUE INDEX IF NOT EXISTS "IX_Products_ProductNumber" ON "Products" ("ProductNumber");
        """);

    if (!await db.Users.AnyAsync(u => u.Username == "admin"))
    {
        db.Users.Add(new User
        {
            Username = "admin",
            PasswordHash = BCrypt.Net.BCrypt.HashPassword("admin123"),
            FullName = "Administrador",
            Role = "Admin",
            ModulePermissions = string.Join(',', ModuleCatalog.All),
            IsActive = true
        });
        await db.SaveChangesAsync();
    }

    var admin = await db.Users.FirstOrDefaultAsync(u => u.Username == "admin");
    var branch = await db.Branches.OrderBy(b => b.Id).FirstOrDefaultAsync();

    if (admin is not null)
    {
        admin.ModulePermissions = string.Join(',', ModuleCatalog.All);
        admin.PermissionProfileId ??= await db.PermissionProfiles
            .Where(p => p.IsAdmin)
            .OrderBy(p => p.Id)
            .Select(p => (int?)p.Id)
            .FirstOrDefaultAsync();

        if (branch is not null)
        {
            var hasAccess = await db.UserBranchAccesses.AnyAsync(x => x.UserId == admin.Id && x.BranchId == branch.Id);
            if (!hasAccess)
            {
                db.UserBranchAccesses.Add(new UserBranchAccess { UserId = admin.Id, BranchId = branch.Id });
            }
        }

        await db.SaveChangesAsync();
    }
}

if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Error");
    app.UseHsts();
}

app.UseHttpsRedirection();
app.UseStaticFiles();
app.UseRouting();
app.UseAuthentication();
app.UseAuthorization();

app.Use(async (ctx, next) =>
{
    if (ctx.User.Identity?.IsAuthenticated == true && !ctx.User.IsInRole("Admin"))
    {
        var path = ctx.Request.Path.Value ?? "/";
        var route = moduleRoutes
            .OrderByDescending(x => x.Key.Length)
            .FirstOrDefault(x => path.StartsWith(x.Key, StringComparison.OrdinalIgnoreCase));

        if (!string.IsNullOrWhiteSpace(route.Key))
        {
            var modules = (ctx.User.FindFirstValue("modules") ?? string.Empty)
                .Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
                .Select(x => x.ToLowerInvariant())
                .ToHashSet();

            if (!modules.Contains(route.Value))
            {
                ctx.Response.Redirect("/Account/Denied");
                return;
            }
        }
    }

    await next();
});

app.MapRazorPages();

app.Run();
